"""
generate_requirements.py
Run from the project root directory (LSTM_DT/):
    python generate_requirements.py
Generates requirements.txt in the same directory.
"""

import ast
import os
import sys
import subprocess
from pathlib import Path

# ── Standard library modules — no installation required ───────────────────────
STDLIB = {
    'os', 'sys', 'json', 'time', 're', 'math', 'datetime', 'pathlib',
    'subprocess', 'argparse', 'typing', 'collections', 'itertools',
    'functools', 'copy', 'io', 'abc', 'ast', 'csv', 'logging', 'warnings',
    'random', 'shutil', 'tempfile', 'traceback', 'inspect', 'types',
    'struct', 'enum', 'dataclasses', 'contextlib', 'threading', 'gc',
    'platform', 'signal', 'pickle', 'hashlib', 'base64', 'urllib',
    'http', 'socket', 'multiprocessing', 'concurrent', 'queue',
    'string', 'textwrap', 'pprint', 'decimal', 'fractions', 'statistics',
    'operator', 'weakref', 'array', 'heapq', 'bisect', 'calendar',
}

# ── Project-internal module prefixes — skip these ─────────────────────────────
LOCAL_PREFIXES = {'LSTM', 'Baseline', 'ModelGenerator', 'Prediction',
                  'Train', 'Combine', 'Compare', 'Run', 'Sensitivity',
                  'Governance', 'BIM', 'Case', 'Supplementary'}

# ── Import name → pip package name mapping ────────────────────────────────────
PKG_MAP = {
    'sklearn':      'scikit-learn',
    'cv2':          'opencv-python',
    'PIL':          'Pillow',
    'yaml':         'PyYAML',
    'dotenv':       'python-dotenv',
    'bs4':          'beautifulsoup4',
    'dateutil':     'python-dateutil',
    'jose':         'python-jose',
    'wx':           'wxPython',
    'gi':           'PyGObject',
    'usaddress':    'usaddress',
    'prophet':      'prophet',
}


def collect_imports(root: Path) -> set:
    imports = set()
    skipped = []

    for py_file in root.rglob('*.py'):
        # Skip virtual environments and cache directories
        parts = py_file.parts
        if any(p in parts for p in ('__pycache__', '.venv', 'venv', 'env',
                                     'site-packages', '.git')):
            continue

        try:
            src = py_file.read_text(encoding='utf-8', errors='ignore')
            tree = ast.parse(src)
        except SyntaxError:
            skipped.append(str(py_file.relative_to(root)))
            continue

        for node in ast.walk(tree):
            if isinstance(node, ast.Import):
                for alias in node.names:
                    imports.add(alias.name.split('.')[0])
            elif isinstance(node, ast.ImportFrom):
                if node.module:
                    imports.add(node.module.split('.')[0])

    if skipped:
        print(f"\n[Skipped {len(skipped)} file(s) due to syntax errors]")
        for f in skipped:
            print(f"  {f}")

    return imports


def resolve_packages(imports: set) -> list:
    third_party = []
    for name in sorted(imports):
        if not name or name.startswith('_'):
            continue
        if name in STDLIB:
            continue
        if any(name.startswith(p) for p in LOCAL_PREFIXES):
            continue
        pip_name = PKG_MAP.get(name, name)
        third_party.append((name, pip_name))
    return third_party


def get_installed_version(pip_name: str) -> str:
    try:
        result = subprocess.run(
            [sys.executable, '-m', 'pip', 'show', pip_name],
            capture_output=True, text=True
        )
        for line in result.stdout.splitlines():
            if line.startswith('Version:'):
                return line.split(':', 1)[1].strip()
    except Exception:
        pass
    return None


def main():
    root = Path(__file__).parent.resolve()
    print(f"Scanning directory: {root}")

    imports = collect_imports(root)
    packages = resolve_packages(imports)

    lines = [
        '# Requirements for LSTM_DT project',
        '# Python >= 3.10',
        '# Generated by generate_requirements.py',
        '# Install: pip install -r requirements.txt',
        '',
    ]

    found, missing = [], []
    for import_name, pip_name in packages:
        ver = get_installed_version(pip_name)
        if ver:
            lines.append(f'{pip_name}>={ver}')
            found.append(pip_name)
        else:
            lines.append(f'# {pip_name}  # not found in current env — verify manually')
            missing.append(pip_name)

    out_path = root / 'requirements.txt'
    out_path.write_text('\n'.join(lines), encoding='utf-8')

    print(f"\n✓ requirements.txt generated: {out_path}")
    print(f"  Packages with version found : {len(found)}")
    if missing:
        print(f"  Packages not found (verify manually): {missing}")


if __name__ == '__main__':
    main()
