"""
generate_requirements.py
放在项目根目录 LSTM_DT/ 下运行：
    python generate_requirements.py
会在同目录生成 requirements.txt
"""

import ast
import os
import sys
import subprocess
from pathlib import Path

# ── 标准库，不需要安装 ─────────────────────────────────────────────────────
STDLIB = {
    'os', 'sys', 'json', 'time', 're', 'math', 'datetime', 'pathlib',
    'subprocess', 'argparse', 'typing', 'collections', 'itertools',
    'functools', 'copy', 'io', 'abc', 'ast', 'csv', 'logging', 'warnings',
    'random', 'shutil', 'tempfile', 'traceback', 'inspect', 'types',
    'struct', 'enum', 'dataclasses', 'contextlib', 'threading', 'gc',
    'platform', 'signal', 'pickle', 'hashlib', 'base64', 'urllib',
    'http', 'socket', 'multiprocessing', 'concurrent', 'queue',
    'string', 'textwrap', 'pprint', 'decimal', 'fractions', 'statistics',
    'operator', 'weakref', 'array', 'heapq', 'bisect', 'calendar',
}

# ── 项目内部模块前缀，跳过 ────────────────────────────────────────────────
LOCAL_PREFIXES = {'LSTM', 'Baseline', 'ModelGenerator', 'Prediction',
                  'Train', 'Combine', 'Compare', 'Run', 'Sensitivity',
                  'Governance', 'BIM', 'Case', 'Supplementary'}

# ── import名 → pip包名映射 ────────────────────────────────────────────────
PKG_MAP = {
    'sklearn':      'scikit-learn',
    'cv2':          'opencv-python',
    'PIL':          'Pillow',
    'yaml':         'PyYAML',
    'dotenv':       'python-dotenv',
    'bs4':          'beautifulsoup4',
    'dateutil':     'python-dateutil',
    'jose':         'python-jose',
    'wx':           'wxPython',
    'gi':           'PyGObject',
    'usaddress':    'usaddress',
    'prophet':      'prophet',
}


def collect_imports(root: Path) -> set:
    imports = set()
    skipped = []

    for py_file in root.rglob('*.py'):
        # 跳过虚拟环境和缓存目录
        parts = py_file.parts
        if any(p in parts for p in ('__pycache__', '.venv', 'venv', 'env',
                                     'site-packages', '.git')):
            continue

        try:
            src = py_file.read_text(encoding='utf-8', errors='ignore')
            tree = ast.parse(src)
        except SyntaxError:
            skipped.append(str(py_file.relative_to(root)))
            continue

        for node in ast.walk(tree):
            if isinstance(node, ast.Import):
                for alias in node.names:
                    imports.add(alias.name.split('.')[0])
            elif isinstance(node, ast.ImportFrom):
                if node.module:
                    imports.add(node.module.split('.')[0])

    if skipped:
        print(f"\n[跳过以下语法错误文件，共{len(skipped)}个]")
        for f in skipped:
            print(f"  {f}")

    return imports


def resolve_packages(imports: set) -> list:
    third_party = []
    for name in sorted(imports):
        if not name or name.startswith('_'):
            continue
        if name in STDLIB:
            continue
        if any(name.startswith(p) for p in LOCAL_PREFIXES):
            continue
        pip_name = PKG_MAP.get(name, name)
        third_party.append((name, pip_name))
    return third_party


def get_installed_version(pip_name: str) -> str:
    try:
        result = subprocess.run(
            [sys.executable, '-m', 'pip', 'show', pip_name],
            capture_output=True, text=True
        )
        for line in result.stdout.splitlines():
            if line.startswith('Version:'):
                return line.split(':', 1)[1].strip()
    except Exception:
        pass
    return None


def main():
    root = Path(__file__).parent.resolve()
    print(f"扫描目录: {root}")

    imports = collect_imports(root)
    packages = resolve_packages(imports)

    lines = [
        '# Requirements for LSTM_DT project',
        f'# Python >= 3.10',
        '# Generated by generate_requirements.py',
        '# Install: pip install -r requirements.txt',
        '',
    ]

    found, missing = [], []
    for import_name, pip_name in packages:
        ver = get_installed_version(pip_name)
        if ver:
            lines.append(f'{pip_name}>={ver}')
            found.append(pip_name)
        else:
            lines.append(f'# {pip_name}  # not found in current env — verify manually')
            missing.append(pip_name)

    out_path = root / 'requirements.txt'
    out_path.write_text('\n'.join(lines), encoding='utf-8')

    print(f"\n✓ requirements.txt 已生成: {out_path}")
    print(f"  已找到版本: {len(found)} 个包")
    if missing:
        print(f"  未找到版本 (需人工确认): {missing}")


if __name__ == '__main__':
    main()
